export function AppFooter() {
  return (
    <footer className="bg-card/50 p-2 text-center text-xs">
      Generated by{' '}
      <a href="https://github.com/solana-foundation/create-solana-dapp" target="_blank" rel="noopener noreferrer">
        create-solana-dapp
      </a>
    </footer>
  );
}
